"use client";

import React, { useState, useEffect, useRef } from 'react';
import { 
  Search, ShieldCheck, Mail, ArrowRight, CheckCircle2, 
  Zap, Database, Chrome, Terminal, Globe, Layers, 
  Lock, Activity, PlayCircle, Shield, ChevronRight, 
  Moon, Sun, Star, Quote, X, Loader2, CheckCircle, 
  Copy, LogOut, UploadCloud, Workflow, PhoneCall, 
  AlertTriangle, PenTool, Server, RefreshCw,
  TrendingDown, TrendingUp, Play, FileUp, MessageSquare,
  MousePointer2
} from 'lucide-react';

/**
 * ============================================================================
 * MAILVAH OUTBOUND SECURITY SUITE - ULTIMATE ENTERPRISE MASTER v4.0
 * NEXT.JS APP ROUTER EDITION
 * ============================================================================
 */

// --- 1. ENTERPRISE DATA CONSTANTS ---
const COMPETITORS = {
  apollo: { 
    id: 'apollo', name: 'Apollo.io', logo: 'A', color: 'bg-slate-900', tagline: 'The bloated CRM giant.', 
    overview: 'Apollo.io is a massive sales platform. While it boasts a huge database, it suffers from severe data decay (~3% monthly) because it relies heavily on cached historical records rather than live verification.', 
    pricing: { competitor: '$49/mo (Credits Expire)', mailvah: '$39/mo (Infinite Rollover)' }, 
    features: [{name: 'Live SMTP Handshake', us: true, them: false}, {name: 'Catch-All Detection', us: true, them: false}, {name: 'Massive B2B Database', us: false, them: true}, {name: 'Unused Credits Roll Over', us: true, them: false}],
    testimonial: { quote: "We were burning through Apollo credits on emails that bounced immediately. Switching to Mailvah dropped our bounce rate from 8% to 0.4% overnight.", author: "Sarah Jenkins, VP Sales" },
    guide: ["1. Export your saved lists from Apollo as a CSV.", "2. Upload the raw CSV directly into the Mailvah Bulk Verifier.", "3. Download the cleaned, 100% verified list and import it into your sending tool."]
  },
  hunter: { 
    id: 'hunter', name: 'Hunter.io', logo: 'H', color: 'bg-orange-500', tagline: 'The pattern guesser.', 
    overview: 'Hunter guesses emails by finding patterns. In modern B2B sales, guessing ruins your domain reputation and guarantees high bounce rates on enterprise targets.', 
    pricing: { competitor: '$34/mo (Strict Limits)', mailvah: '$39/mo (Massive Bulk Volume)' }, 
    features: [{name: 'Guaranteed 99% Deliverability', us: true, them: false}, {name: 'Pattern-Based Guessing', us: false, them: true}, {name: 'Spam-Proof Composer', us: true, them: false}, {name: 'DNSBL Domain Monitoring', us: true, them: false}],
    testimonial: { quote: "Hunter was great for finding generic info@ emails, but it ruined our sender reputation when guessing executive formats. Mailvah's live ping is a lifesaver.", author: "David Chen, Growth Lead" },
    guide: ["1. Cancel your Hunter.io auto-renew to stop wasting budget.", "2. Connect Mailvah to your CRM for 1-Click purging.", "3. Start verifying domains with absolute certainty."]
  },
  skrapp: { 
    id: 'skrapp', name: 'Skrapp.io', logo: 'S', color: 'bg-blue-400', tagline: 'The LinkedIn scraper.', 
    overview: 'Skrapp relies on scraped lists. B2B data goes stale fast, and Skrapp struggles with modern Catch-All domains and enterprise firewalls.', 
    pricing: { competitor: '$49/mo (High Cost-Per-Lead)', mailvah: '$39/mo (Fractions of a Cent)' }, 
    features: [{name: 'Real-Time Port 25 Verification', us: true, them: false}, {name: 'LinkedIn Static Scraping', us: false, them: true}, {name: 'Bulk CSV Processing up to 100k', us: true, them: false}, {name: 'Enterprise API Access', us: true, them: false}],
    testimonial: { quote: "Skrapp's lists went stale in weeks. With Mailvah, we verify our targets the exact second before we launch the campaign.", author: "Elena Rodriguez, Agency Founder" },
    guide: ["1. Take any legacy list generated by Skrapp.", "2. Run it through Mailvah to filter out the dead domains and catch-alls.", "3. Enjoy a pristine, zero-bounce campaign."]
  },
  snov: { 
    id: 'snov', name: 'Snov.io', logo: 'S', color: 'bg-purple-500', tagline: 'The complex sequencer.', 
    overview: 'Snov is built for complex drip campaigns; its verification engine is a secondary feature lacking the bare-metal speed and accuracy required for scale.', 
    pricing: { competitor: '$39/mo (Split Credits)', mailvah: '$39/mo (Pure Verification)' }, 
    features: [{name: 'Dedicated Verification Infrastructure', us: true, them: false}, {name: 'Built-in Drip Campaigns', us: false, them: true}, {name: 'Bounce Auto-Refunds', us: true, them: false}, {name: 'Sub-200ms API Latency', us: true, them: false}],
    testimonial: { quote: "We already use Smartlead for sending. Snov was overkill. Mailvah integrates perfectly as our pure verification layer.", author: "Marcus T., Head of Outbound" },
    guide: ["1. Keep your dedicated sending platform (Smartlead, Instantly, etc).", "2. Route your pre-campaign lists through the Mailvah Bulk API.", "3. Push the cleaned leads directly into your sequencing tool."]
  }
};

const LEGAL_DATA = {
  privacy: { 
    title: "Privacy Policy", date: "March 27, 2026",
    intro: "At Donmican Technology Ltd. ('Mailvah'), we are fundamentally committed to protecting your privacy. This policy details how we collect, use, and safeguard your data.", 
    sections: [
      { heading: "1. Comprehensive Data Categories", body: ["Customer Account Data: We collect your name, business email, corporate entity name, and billing details (processed securely via our payment gateways). Purpose: Account administration.", "Verification Payload Data (Transient): CSV files containing raw email lists uploaded by the User. Purpose: To execute SMTP handshakes and deliverability checks. Retention: Processed entirely in-memory on bare-metal servers. Cached results are held for a maximum of 7 days to optimize network load before permanent automated deletion. We do not use this data to train models or sell to third parties.", "Platform Telemetry Data: IP addresses, user agent strings, API request timestamps, and UI interaction logs. Purpose: Security monitoring, rate-limit enforcement, and fraud prevention."] },
      { heading: "2. Authorized Sub-Processors", body: ["Hetzner Online GmbH (Germany): Primary bare-metal compute and SMTP processing. Purpose: Verification execution.", "Supabase, Inc. (USA/EU region): Postgres database hosting. Purpose: User account and persistent credit ledger storage.", "Cloudflare, Inc. (USA): Content Delivery Network (CDN) and Web Application Firewall (WAF). Purpose: DDoS protection and secure edge routing.", "Flutterwave / Stripe (Global): Secure PCI-DSS compliant payment processing."] },
      { heading: "3. International Data Transfers", body: ["Mailvah operates globally. When personal data originating from the EEA, the UK, or Switzerland is transferred outside these regions, we ensure protection utilizing Standard Contractual Clauses (SCCs), supplemented by rigorous Transfer Impact Assessments (TIAs) ensuring encryption in transit (TLS 1.3)."] },
      { heading: "4. Cookie & Local Storage Policy", body: ["We limit tracking strictly to functional and security requirements.", "__mailvah_sess (Strictly Necessary): 256-bit encrypted JWT token maintaining the user's active session state. Expires in 24 hours.", "__cf_bm (Security): Cloudflare bot-management cookie to detect malicious automated traffic. Expires in 30 minutes.", "ph_ (Analytics): PostHog telemetry to track dashboard feature usage. Users may opt out via the platform settings."] }
    ]
  },
  terms: { 
    title: "Terms of Service", date: "March 27, 2026",
    intro: "By accessing the Mailvah platform, APIs, or services, you agree to be bound by these Terms of Service. Please read them carefully.", 
    sections: [
      { heading: "1. Strict Acceptable Use Policy (AUP)", body: ["Mailvah is an outbound security and deliverability tool. You explicitly agree NOT to use our platform to facilitate spam, phishing, harassment, or the distribution of malware.", "You are prohibited from verifying illegally scraped, purchased, or third-party rented databases.", "Violation Consequence: Mailvah utilizes automated heuristics to detect toxic list uploads (e.g., lists with >40% hard bounce rates). Violations of this AUP result in immediate account suspension, forfeiture of all rollover credits, and zero eligibility for refunds."] },
      { heading: "2. Subscriptions, SLAs, and Rollover", body: ["Rollover Credits: Unlike legacy providers, unused verification credits on Mailvah paid plans roll over to the next billing cycle, provided your subscription remains active.", "Uptime Commitment (SLA): Mailvah guarantees a 99.9% Monthly Uptime Percentage for our core Verification API. If we fail to meet this SLA, enterprise and paid users are eligible for Service Credits (up to 100% of the monthly fee for < 95.0% uptime)."] },
      { heading: "3. 30-Day Money-Back Guarantee", body: ["If you are not satisfied with the accuracy of our verification engine, you may request a full refund within 30 days of your initial purchase. Refunds are processed to the original payment method."] },
      { heading: "4. API Rate Limits & Fair Use", body: ["To protect our infrastructure, API endpoints are rate-limited. Sandbox Tier: Max 10 requests per second (RPS). Pro Network Tier: Max 500 RPS. Sustained spikes exceeding these limits will result in temporary HTTP 429 responses."] },
      { heading: "5. Dispute Resolution & Governing Law", body: ["Any dispute arising out of these Terms shall be settled by binding arbitration administered by the International Chamber of Commerce (ICC). The governing law shall be the laws applicable to Donmican Technology Ltd., without regard to conflict of law principles."] }
    ]
  },
  security: {
    title: "Security Overview", date: "March 27, 2026",
    intro: "Enterprise security is not an afterthought at Mailvah. We employ modern cryptographic standards, strict access controls, and bare-metal isolation.",
    sections: [
      { heading: "1. Data Encryption Standards", body: ["In Transit: All communications between your browser, our APIs, and our database are encrypted using TLS 1.3 with perfect forward secrecy.", "At Rest: All sensitive data stored within our databases (including API keys and billing details) is encrypted using AES-256 standard encryption."] },
      { heading: "2. Infrastructure & Application Security", body: ["Our database layers are hosted on SOC 2 Type II compliant data centers.", "Verification workers operate on isolated, bare-metal servers. These workers process verification payloads in memory and communicate securely with our central database via authenticated, private networks.", "We utilize Row-Level Security (RLS) policies within our Postgres database. This guarantees users can only query or modify data associated with their Workspace ID."] },
      { heading: "3. Vulnerability Management & Pen-Testing", body: ["We continuously monitor our dependencies for CVEs and deploy security patches within 24 hours of release.", "Mailvah engages certified, independent third-party security firms annually to conduct rigorous gray-box penetration tests on our public APIs. Summaries are available to Enterprise clients under NDA."] },
      { heading: "4. Incident Response Plan (IRP)", body: ["Our infrastructure is monitored 24/7/365. In the event of an anomaly, automated kill-switches can instantly revoke API keys, disconnect compromised workers, and block malicious IPs at the Cloudflare WAF level."] }
    ]
  },
  gdpr: {
    title: "GDPR Compliance", date: "March 27, 2026",
    intro: "Donmican Technology Ltd. is fundamentally committed to compliance with the General Data Protection Regulation (GDPR) and similar global privacy frameworks.",
    sections: [
      { heading: "1. Lawful Basis for Processing", body: ["Mailvah processes Business-to-Business (B2B) contact data under the lawful basis of 'Legitimate Interest' (Article 6(1)(f) of the GDPR).", "Our services are designed to facilitate legitimate B2B communication. We strictly prohibit the use of our platform for consumer spam."] },
      { heading: "2. Our Role (Controller vs Processor)", body: ["Data Controller: We act as a Data Controller for the personal information of our direct customers (e.g., your account billing details).", "Data Processor: We act as a Data Processor for the contact lists you upload to our Bulk Verifier. You maintain ownership of this data, and we process it strictly to provide the verification service."] },
      { heading: "3. 72-Hour Breach Notification", body: ["In the event of a confirmed personal data breach, Mailvah’s Incident Response Team initiates a strict 72-hour protocol. We will formally notify the relevant Supervisory Authority and email all affected Data Controllers (our Users) with specific details and mitigations applied."] },
      { heading: "4. Data Subject Requests", body: ["We provide automated tools for users to manage, export, and delete their data. External data subjects wishing to know if their professional email is in our temporary verification cache may submit a request to our DPO, fulfilled within the legally required 30-day window."] }
    ]
  }
};

const spamWords = ['free', 'guarantee', 'urgent', 'act now', 'buy', 'discount', '100%', 'click here', 'winner', 'risk-free', 'opportunity', 'cash', 'crypto', 'investment', 'lowest price', 'no hidden costs', 'obligation', 'promise', 'save big', 'special promotion'];

// --- 2. SHARED UI COMPONENTS & LOGIC ---

// Infinite FOMO Engine
const FomoPopup = () => {
  const [fomo, setFomo] = useState(null);
  const [visible, setVisible] = useState(false);

  const names = ['Sarah', 'David', 'Alex', 'Jessica', 'Michael', 'Emily', 'Chris', 'Amanda', 'John', 'Rachel', 'Olorunleke', 'Elena', 'Marcus'];
  const companies = ['Linear', 'Stripe', 'Vercel', 'HubSpot', 'Salesforce', 'Acme Corp', 'TechFlow', 'Growthly', 'Scaleup', 'PhantomBuster', 'ZoomInfo'];
  const actions = ['just verified 10,000 emails', 'purged 4,500 bounces via CRM', 'upgraded to the Pro Network', 'cleaned a scraped list', 'caught 300+ spam traps'];

  useEffect(() => {
    const triggerFomo = () => {
      const name = names[Math.floor(Math.random() * names.length)];
      const company = companies[Math.floor(Math.random() * companies.length)];
      const action = actions[Math.floor(Math.random() * actions.length)];
      const time = Math.floor(Math.random() * 12) + 1;
      
      setFomo({ name, company, action, time });
      setVisible(true);
      
      setTimeout(() => setVisible(false), 5000);
      setTimeout(triggerFomo, Math.random() * 8000 + 8000); // Trigger every 8-16s
    };
    const init = setTimeout(triggerFomo, 3000);
    return () => clearTimeout(init);
  }, []);

  if (!fomo) return null;

  return (
    <div className={`fixed bottom-6 left-6 z-[100] transition-all duration-500 transform ${visible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0 pointer-events-none'}`}>
      <div className="bg-slate-900 dark:bg-slate-800 border border-slate-700 shadow-2xl rounded-2xl p-4 flex items-center gap-4 max-w-sm">
        <div className="w-10 h-10 bg-emerald-500/20 rounded-full flex items-center justify-center shrink-0">
          <CheckCircle2 className="w-5 h-5 text-emerald-400"/>
        </div>
        <div>
          <p className="text-sm font-medium text-white">
            <span className="font-bold">{fomo.name}</span> at <span className="font-bold text-blue-400">{fomo.company}</span> {fomo.action}.
          </p>
          <p className="text-xs text-slate-400 mt-0.5">{fomo.time} min ago</p>
        </div>
      </div>
    </div>
  );
};

const Badge = ({ children, color = 'blue' }) => {
  const colors = {
    blue: "bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400 border-blue-200/50 dark:border-blue-800/50",
    emerald: "bg-emerald-50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 border-emerald-200/50 dark:border-emerald-800/50",
    purple: "bg-purple-50 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 border-purple-200/50 dark:border-purple-800/50",
    gold: "bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 border-amber-200/50 dark:border-amber-800/50",
  };
  return <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-black uppercase tracking-widest border ${colors[color]} mb-4`}>{children}</div>;
};

const Navbar = ({ isDark, toggleTheme, isLoggedIn, onOpenAuth, navigate, currentRoute }) => {
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const isDashboard = currentRoute.path === 'dashboard';

  return (
    <nav className={`fixed top-0 w-full z-[60] transition-all duration-300 ${scrolled ? (isDark ? 'glass-nav-dark py-4 shadow-lg shadow-black/10' : 'glass-nav-light py-4 shadow-sm') : 'bg-transparent py-6'} ${isDashboard ? 'lg:hidden' : ''}`}>
      <div className="max-w-7xl mx-auto px-6 flex items-center justify-between">
        <div onClick={() => navigate('home')} className="flex items-center gap-3 cursor-pointer group">
          <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center shadow-lg group-hover:scale-105 transition-transform"><Mail className="w-5 h-5 text-white" /></div>
          <span className="text-2xl font-black tracking-tight text-slate-900 dark:text-white">Mailvah.</span>
        </div>
        {!isDashboard && (
          <div className="hidden lg:flex items-center gap-8 px-6 py-2 rounded-full border border-slate-200/60 dark:border-slate-700/50 bg-white/50 dark:bg-slate-800/50 backdrop-blur-md">
            <button onClick={() => navigate('home', 'features')} className="text-sm font-bold text-slate-600 dark:text-slate-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Platform</button>
            <button onClick={() => navigate('compare', 'apollo')} className="text-sm font-bold text-slate-600 dark:text-slate-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Compare</button>
            <button onClick={() => navigate('home', 'pricing')} className="text-sm font-bold text-slate-600 dark:text-slate-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Pricing</button>
          </div>
        )}
        <div className="flex items-center gap-4">
          <button onClick={toggleTheme} className="p-2 rounded-full text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">{isDark ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}</button>
          {isLoggedIn ? (
             <button onClick={() => navigate('dashboard')} className="bg-blue-600 text-white px-5 py-2.5 rounded-xl text-sm font-black shadow-md flex items-center gap-2 hover:bg-blue-500 transition-colors">Dashboard <ArrowRight className="w-4 h-4"/></button>
          ) : (
            <>
              <button onClick={() => onOpenAuth('login')} className="text-sm font-bold text-slate-600 dark:text-slate-300 hidden sm:block hover:text-blue-600 transition-colors">Log in</button>
              <button onClick={() => onOpenAuth('signup')} className="bg-slate-900 dark:bg-white text-white dark:text-slate-900 px-6 py-2.5 rounded-xl text-sm font-black shadow-lg hover:scale-105 transition-transform">Start for free</button>
            </>
          )}
        </div>
      </div>
    </nav>
  );
};

const Footer = ({ navigate }) => (
  <footer className="bg-slate-950 dark:bg-[#050810] pt-24 pb-12 border-t border-slate-900 dark:border-slate-800 relative z-50">
    <div className="max-w-7xl mx-auto px-6">
      <div className="grid grid-cols-2 md:grid-cols-12 gap-x-8 gap-y-12 mb-20">
        <div className="col-span-2 md:col-span-4">
          <div onClick={() => navigate('home')} className="flex items-center gap-2.5 mb-6 cursor-pointer">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center shadow-lg"><Mail className="w-4 h-4 text-white" /></div>
            <span className="text-2xl font-black text-white tracking-tight">Mailvah.</span>
          </div>
          <p className="text-slate-400 text-sm max-w-xs leading-relaxed font-medium mb-6">The most affordable, high-accuracy Outbound Security Suite on the market. Find verified business emails, protect your domains, and grow your pipeline.</p>
          <div className="bg-slate-900 border border-slate-800 p-4 rounded-2xl mb-6 max-w-xs">
            <div className="flex items-center gap-2 text-sm font-bold text-white mb-1">Affordable by design.</div>
            <div className="text-xs text-slate-400 font-medium">We own our bare-metal infrastructure, which means we can pass massive database savings directly down to you.</div>
          </div>
        </div>
        
        <div className="md:col-span-2">
          <h4 className="text-white font-bold mb-6 tracking-wide">Product</h4>
          <ul className="space-y-4 text-sm font-medium text-slate-400 flex flex-col items-start">
            <li><button onClick={() => navigate('home', 'features')} className="hover:text-white transition-colors">Features</button></li>
            <li><button onClick={() => navigate('home', 'pricing')} className="hover:text-white transition-colors">Pricing</button></li>
            <li><button className="hover:text-white transition-colors">Chrome Extension</button></li>
          </ul>
        </div>
        
        <div className="md:col-span-2">
          <h4 className="text-white font-bold mb-6 tracking-wide">Compare</h4>
          <ul className="space-y-4 text-sm font-medium text-slate-400 flex flex-col items-start">
            <li><button onClick={() => navigate('compare', 'apollo')} className="hover:text-white transition-colors">Mailvah vs Apollo</button></li>
            <li><button onClick={() => navigate('compare', 'hunter')} className="hover:text-white transition-colors">Mailvah vs Hunter</button></li>
            <li><button onClick={() => navigate('compare', 'skrapp')} className="hover:text-white transition-colors">Mailvah vs Skrapp</button></li>
            <li><button onClick={() => navigate('compare', 'snov')} className="hover:text-white transition-colors">Mailvah vs Snov.io</button></li>
          </ul>
        </div>

        <div className="md:col-span-2">
          <h4 className="text-white font-bold mb-6 tracking-wide">Legal</h4>
          <ul className="space-y-4 text-sm font-medium text-slate-400 flex flex-col items-start">
            <li><button onClick={() => navigate('legal', 'privacy')} className="hover:text-white transition-colors">Privacy Policy</button></li>
            <li><button onClick={() => navigate('legal', 'terms')} className="hover:text-white transition-colors">Terms of Service</button></li>
            <li><button onClick={() => navigate('legal', 'gdpr')} className="hover:text-white transition-colors">GDPR</button></li>
            <li><button onClick={() => navigate('legal', 'security')} className="hover:text-white transition-colors">Security</button></li>
          </ul>
        </div>
      </div>
      
      <div className="border-t border-slate-900 dark:border-slate-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-sm font-medium text-slate-600">
        <p>© {new Date().getFullYear()} Donmican Technology Ltd. All rights reserved.</p>
        <div className="flex items-center gap-6"><span className="flex items-center gap-1.5"><Shield className="w-4 h-4"/> SOC 2 Type II</span><span className="flex items-center gap-1.5"><Lock className="w-4 h-4"/> 256-bit Encryption</span></div>
      </div>
    </div>
  </footer>
);

const AuthModal = ({ isOpen, onClose, initialMode, onLoginSuccess }) => {
  const [mode, setMode] = useState(initialMode);
  const [loading, setLoading] = useState(false);
  useEffect(() => { setMode(initialMode); }, [initialMode]);
  if (!isOpen) return null;

  const handleAuth = (e) => {
    e.preventDefault(); setLoading(true);
    setTimeout(() => { setLoading(false); onLoginSuccess(); onClose(); }, 1200);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={onClose}></div>
      <div className="relative bg-white dark:bg-slate-900 w-full max-w-md rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 p-8 toast-enter overflow-hidden">
        <div className="absolute top-0 right-0 w-48 h-48 bg-blue-500/10 rounded-full blur-[40px] pointer-events-none"></div>
        <button onClick={onClose} className="absolute top-4 right-4 p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full z-10 transition-colors"><X className="w-5 h-5"/></button>
        <div className="flex items-center gap-2 mb-8 relative z-10"><div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center shadow-lg"><Mail className="w-4 h-4 text-white" /></div><span className="text-xl font-black tracking-tight text-slate-900 dark:text-white">Mailvah.</span></div>
        <h3 className="text-2xl font-black mb-2 relative z-10 text-slate-900 dark:text-white">{mode === 'login' ? 'Welcome back' : 'Create your account'}</h3>
        <p className="text-sm font-medium text-slate-500 mb-8 relative z-10">{mode === 'login' ? 'Enter your details to access your dashboard.' : 'Start finding verified leads today with 150 free credits.'}</p>
        <form onSubmit={handleAuth} className="space-y-4 relative z-10">
          <div><label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1.5">Email Address</label><input type="email" required placeholder="you@company.com" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500 font-medium text-slate-900 dark:text-white" /></div>
          <div><label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1.5">Password</label><input type="password" required placeholder="••••••••" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500 font-medium text-slate-900 dark:text-white" /></div>
          <button type="submit" disabled={loading} className="w-full bg-blue-600 hover:bg-blue-700 text-white font-black py-4 rounded-xl shadow-lg shadow-blue-600/20 flex justify-center items-center gap-2 mt-2 transition-all hover:scale-[1.02]">{loading ? <Loader2 className="w-5 h-5 animate-spin"/> : (mode === 'login' ? 'Sign In' : 'Create Account')}</button>
        </form>
        <div className="mt-6 text-center text-sm font-medium text-slate-500 relative z-10">{mode === 'login' ? "Don't have an account? " : "Already have an account? "}<button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')} className="font-bold text-blue-600 hover:underline">{mode === 'login' ? 'Sign up' : 'Log in'}</button></div>
      </div>
    </div>
  );
};

// --- THE 4 TAB DEMO COMPONENTS ---
const DemoSMTP = () => {
  const [logs, setLogs] = useState([]);
  useEffect(() => {
    const sequence = [`[SYSTEM] Initiating Waterfall for stripe.com...`, `[DNS] Locating MX records... Found mx.stripe.com.`, `[NETWORK] TCP handshake on Port 25...`, `[SMTP] -> EHLO verify.mailvah.com`, `[SMTP] <- 250 OK`, `[SMTP] -> RCPT TO:<j.doe@stripe.com>`, `[SMTP] <- 250 2.1.5 Recipient OK`, `[SUCCESS] Mailbox exists. Safe to send.`];
    let i = 0; const t = setInterval(() => { if (i < sequence.length) { setLogs(prev => [...prev, sequence[i]]); i++; } else clearInterval(t); }, 600);
    return () => clearInterval(t);
  }, []);
  return (
    <div className="h-full flex flex-col font-mono text-sm p-2">
      <div className="text-slate-400 mb-4 flex items-center gap-2"><Terminal className="w-4 h-4"/> Live Verification Terminal</div>
      <div className="flex-1 space-y-2 overflow-y-auto">
        {logs.map((log, idx) => (
          <div key={idx} className={log?.includes('<- 250') || log?.includes('[SUCCESS]') ? "text-emerald-400 font-bold animate-in fade-in slide-in-from-bottom-2" : "text-slate-300 animate-in fade-in slide-in-from-bottom-2"}>{log}</div>
        ))}
        {logs.length < 8 && <div className="w-2 h-4 bg-emerald-500 animate-pulse mt-2"></div>}
      </div>
    </div>
  );
};

const DemoBulk = () => {
  const [progress, setProgress] = useState(0);
  useEffect(() => { const t = setInterval(() => setProgress(p => p < 100 ? p + 20 : 100), 1000); return () => clearInterval(t); }, []);
  return (
    <div className="h-full flex flex-col p-2">
      <div className="text-slate-400 mb-4 flex items-center gap-2"><UploadCloud className="w-4 h-4"/> Processing Bulk CSV</div>
      {progress < 100 ? (
        <div className="flex-1 flex flex-col justify-center items-center"><Activity className="w-10 h-10 text-blue-500 animate-spin mb-4"/><div className="w-3/4 bg-slate-800 rounded-full h-2 mb-2"><div className="bg-blue-500 h-2 rounded-full transition-all duration-300" style={{width: `${progress}%`}}></div></div><div className="text-blue-400 font-bold">{progress}% Complete</div></div>
      ) : (
        <div className="flex-1 flex flex-col justify-center animate-in fade-in"><div className="bg-emerald-500/10 border border-emerald-500/30 p-4 rounded-xl mb-4 text-center"><CheckCircle className="w-8 h-8 text-emerald-500 mx-auto mb-2"/><div className="text-emerald-400 font-bold">10,000 Rows Cleaned</div></div><div className="grid grid-cols-2 gap-4 text-center"><div className="bg-slate-800 p-3 rounded-lg"><div className="text-2xl font-black text-white">8,420</div><div className="text-xs text-emerald-400 font-bold">Diamond Leads</div></div><div className="bg-slate-800 p-3 rounded-lg"><div className="text-2xl font-black text-white">1,580</div><div className="text-xs text-red-400 font-bold">Bounces Removed</div></div></div></div>
      )}
    </div>
  );
};

const DemoDomain = () => {
  const [step, setStep] = useState(0);
  useEffect(() => { const t = setInterval(() => setStep(s => s < 3 ? s + 1 : 3), 1500); return () => clearInterval(t); }, []);
  return (
    <div className="h-full flex flex-col p-2 font-mono text-sm">
      <div className="text-slate-400 mb-4 flex items-center gap-2"><ShieldCheck className="w-4 h-4"/> Checking Domain Health</div>
      <div className="space-y-4">
        <div className="flex justify-between"><span>Querying Spamhaus ZEN...</span>{step > 0 ? <span className="text-emerald-400 font-bold">NXDOMAIN (Clean)</span> : <span className="text-slate-500 animate-pulse">Waiting...</span>}</div>
        <div className="flex justify-between"><span>Querying SURBL...</span>{step > 1 ? <span className="text-emerald-400 font-bold">NXDOMAIN (Clean)</span> : <span className="text-slate-500 animate-pulse">Waiting...</span>}</div>
        <div className="flex justify-between"><span>Querying Barracuda...</span>{step > 2 ? <span className="text-emerald-400 font-bold">NXDOMAIN (Clean)</span> : <span className="text-slate-500 animate-pulse">Waiting...</span>}</div>
      </div>
      {step === 3 && <div className="mt-auto bg-emerald-500/20 text-emerald-400 p-3 rounded-lg flex items-center justify-center gap-2 font-bold animate-in fade-in"><CheckCircle2 className="w-5 h-5"/> outbound-acme.com is Safe</div>}
    </div>
  );
};

const DemoComposer = () => {
  const [showWarning, setShowWarning] = useState(false);
  useEffect(() => { const t = setTimeout(() => setShowWarning(true), 3000); return () => clearTimeout(t); }, []);
  return (
    <div className="h-full flex flex-col p-2">
      <div className="text-slate-400 mb-4 flex items-center gap-2"><PenTool className="w-4 h-4"/> Spam-Proof Composer</div>
      <div className="bg-slate-800 rounded-xl p-4 text-slate-300 flex-1 relative font-mono text-sm leading-relaxed">
        We help agencies scale their revenue.<br/><br/>We offer a {showWarning ? <span className="spam-highlight">100% free</span> : "100% free"} trial and a full {showWarning ? <span className="spam-highlight">money-back guarantee</span> : "money-back guarantee"} if you sign up today.
        {showWarning && <div className="absolute bottom-4 left-4 right-4 bg-red-500/20 border border-red-500/50 p-3 rounded-lg flex items-start gap-3 animate-in slide-in-from-bottom-4"><AlertTriangle className="w-5 h-5 text-red-400 shrink-0"/><div className="text-xs text-red-300 font-bold">Google Spam Filters detected 2 dangerous triggers. Remove "100% free" and "guarantee" to ensure inbox placement.</div></div>}
      </div>
    </div>
  );
};

const LivePlatformTour = () => {
  const [activeDemo, setActiveDemo] = useState(0);
  const [key, setKey] = useState(0); 
  const tabs = [{ id: 0, name: "1. Waterfall Engine", icon: <Terminal className="w-4 h-4"/> }, { id: 1, name: "2. Bulk Uploads", icon: <UploadCloud className="w-4 h-4"/> }, { id: 2, name: "3. Domain Monitor", icon: <ShieldCheck className="w-4 h-4"/> }, { id: 3, name: "4. Spam Composer", icon: <PenTool className="w-4 h-4"/> }];
  useEffect(() => { const timer = setInterval(() => { setActiveDemo(prev => (prev + 1) % 4); setKey(prev => prev + 1); }, 8000); return () => clearInterval(timer); }, []);

  return (
    <section className="py-24 bg-slate-900 dark:bg-[#080b13] border-y border-slate-800 relative overflow-hidden">
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-blue-600/10 rounded-full blur-[100px] pointer-events-none"></div>
      <div className="max-w-6xl mx-auto px-6 relative z-10">
        <div className="text-center mb-16">
          <Badge color="blue">30-Second Platform Tour</Badge>
          <h2 className="text-4xl md:text-5xl font-black text-white mb-4 tracking-tight">Watch the infrastructure in action.</h2>
          <p className="text-lg text-slate-400 font-medium max-w-2xl mx-auto">This isn't a mockup. This is the exact logic our backend executes to protect your pipeline.</p>
        </div>

        <div className="bg-[#0f172a] rounded-[2rem] border border-slate-700 shadow-2xl shadow-blue-900/20 overflow-hidden flex flex-col h-[450px]">
          <div className="bg-slate-900 border-b border-slate-800 flex overflow-x-auto scrollbar-hide relative">
            {tabs.map(tab => (
              <button key={tab.id} onClick={() => {setActiveDemo(tab.id); setKey(prev => prev+1);}} className={`flex items-center gap-2 px-8 py-5 text-sm font-bold transition-colors whitespace-nowrap relative ${activeDemo === tab.id ? 'text-white bg-slate-800' : 'text-slate-500 hover:text-slate-300'}`}>
                {tab.icon} {tab.name}
                {activeDemo === tab.id && <div className="absolute bottom-0 left-0 h-0.5 bg-blue-500 animate-progress"></div>}
              </button>
            ))}
          </div>
          <div className="flex-1 p-8 bg-[#0f172a] relative">
            <div key={key} className="h-full">
               {activeDemo === 0 && <DemoSMTP />}
               {activeDemo === 1 && <DemoBulk />}
               {activeDemo === 2 && <DemoDomain />}
               {activeDemo === 3 && <DemoComposer />}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

// DEV API Live Log Component
const LiveDevLogs = () => {
  const [logs, setLogs] = useState([
    { email: 'founder@scaleup.com', latency: 142, status: 'valid', score: 99 },
    { email: 'info@acmecorp.net', latency: 118, status: 'catch-all', score: 45 }
  ]);
  
  useEffect(() => {
    const domains = ['stripe.com', 'apple.com', 'linear.app', 'vercel.com', 'hubspot.com'];
    const names = ['ceo', 'cto', 'admin', 'contact', 'sales'];
    
    const int = setInterval(() => {
      setLogs(prev => {
        const newLog = {
          email: `${names[Math.floor(Math.random()*names.length)]}@${domains[Math.floor(Math.random()*domains.length)]}`,
          latency: Math.floor(Math.random() * 80) + 100,
          status: Math.random() > 0.2 ? 'valid' : 'bounced',
          score: Math.floor(Math.random() * 20) + 80
        };
        const newLogs = [...prev, newLog];
        if (newLogs.length > 6) newLogs.shift();
        return newLogs;
      });
    }, 1500);
    return () => clearInterval(int);
  }, []);

  return (
    <div className="space-y-4">
      <div className="text-slate-400 mb-6">$ tail -f /var/log/mailvah-engine.log</div>
      {logs.map((log, i) => (
        <div key={i} className="animate-in fade-in slide-in-from-bottom-2">
          <span className="text-emerald-400">[200 OK]</span> <span className="text-slate-300">POST /v1/verify</span> <span className="text-blue-400">{"{"}"email": "{log.email}"{"}"}</span> <br/>
          <span className="text-slate-500">↳ status: <span className={log.status === 'valid' ? 'text-emerald-500' : 'text-red-500'}>{log.status}</span> | latency: {log.latency}ms | score: {log.score}</span>
        </div>
      ))}
    </div>
  );
};


// --- 3. PAGE COMPONENTS ---

const LandingPage = ({ onOpenAuth, onNavigateToPricing }) => {
  const [domain, setDomain] = useState('');
  const [placeholderText, setPlaceholderText] = useState('');
  const [searchState, setSearchState] = useState('idle'); 
  const [annualBilling, setAnnualBilling] = useState(true);
  const [sliderIndex, setSliderIndex] = useState(1);
  const [viewMode, setViewMode] = useState('sales'); // 'sales' or 'dev'

  useEffect(() => {
    const topDomains = ["stripe.com", "apple.com", "airbnb.com", "netflix.com", "linear.app"];
    let currentDomainIdx = 0; let currentCharIdx = 0; let isDeleting = false; let typingTimer;
    const type = () => {
      const currentDomain = topDomains[currentDomainIdx];
      if (isDeleting) {
        setPlaceholderText(currentDomain.substring(0, currentCharIdx - 1)); currentCharIdx--;
        if (currentCharIdx === 0) { isDeleting = false; currentDomainIdx = (currentDomainIdx + 1) % topDomains.length; typingTimer = setTimeout(type, 500); } else { typingTimer = setTimeout(type, 50); }
      } else {
        setPlaceholderText(currentDomain.substring(0, currentCharIdx + 1)); currentCharIdx++;
        if (currentCharIdx === currentDomain.length) { isDeleting = true; typingTimer = setTimeout(type, 2000); } else { typingTimer = setTimeout(type, 100); }
      }
    };
    typingTimer = setTimeout(type, 500);
    return () => clearTimeout(typingTimer);
  }, []);

  const handleManualSearch = (e) => { 
    e.preventDefault(); 
    if(!domain) return;
    setSearchState('scanning');
    
    const cleanTarget = domain.replace(/^(?:https?:\/\/)?(?:www\.)?/i, "").split('/')[0] || 'domain.com';
    const isValid = /^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$/.test(cleanTarget);
    
    setTimeout(() => setSearchState(isValid ? 'result' : 'invalid'), 3000);
  };
  
  const cleanDomain = domain.replace(/^(?:https?:\/\/)?(?:www\.)?/i, "").split('/')[0] || 'stripe.com';
  
  // Pricing & ROI logic
  const pricingTiers = [{ credits: 1500, price: 39 }, { credits: 5000, price: 79 }, { credits: 20000, price: 179 }, { credits: 50000, price: 299 }, { credits: 100000, price: 499 }];
  const currentTier = pricingTiers[sliderIndex];
  const displayPrice = annualBilling ? Math.floor(currentTier.price * 0.8) : currentTier.price;
  
  const volumes = [1000, 5000, 20000, 50000, 100000];
  const volume = volumes[sliderIndex];
  const bounceRate = 8;
  const wastedLeads = Math.floor(volume * (bounceRate / 100));
  const savings = Math.floor(wastedLeads * 0.6); // Roughly $0.60 per lead value saved

  return (
    <div className="page-transition relative">
      <FomoPopup />

      {/* ENTERPRISE HERO SECTION */}
      <section className="relative pt-32 pb-32 lg:pt-48 lg:pb-40 overflow-hidden flex flex-col items-center text-center px-4">
        <div className="absolute inset-0 bg-grid-light dark:bg-grid-dark bg-[size:40px_40px] [mask-image:linear-gradient(to_bottom,white,transparent)] -z-20"></div>
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-gradient-to-b from-blue-500/20 to-transparent dark:from-blue-600/20 rounded-full blur-[120px] -z-10"></div>
        
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/80 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-700 shadow-sm text-slate-700 dark:text-slate-300 text-sm font-bold mb-8 backdrop-blur-sm animate-in fade-in slide-in-from-bottom-4 duration-700">
          <span className="flex h-2.5 w-2.5 relative"><span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span><span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500"></span></span>
          Mailvah Engine 2.0 is Live
        </div>
        
        <h1 className="text-6xl md:text-7xl lg:text-[5.5rem] font-black tracking-tighter text-slate-900 dark:text-white mb-8 max-w-5xl leading-[1.05] animate-in fade-in slide-in-from-bottom-6 duration-700 delay-100">
          Never bounce again.<br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-500 dark:from-blue-400 dark:to-indigo-400">Scale with absolute certainty.</span>
        </h1>
        
        <p className="text-xl md:text-2xl text-slate-600 dark:text-slate-400 mb-10 max-w-3xl font-medium leading-relaxed animate-in fade-in slide-in-from-bottom-8 duration-700 delay-200">
          The only outbound security suite that executes live SMTP handshakes over bare-metal servers. Stop relying on stale databases and protect your sender reputation.
        </p>

        <div className="w-full max-w-2xl mx-auto relative mb-12 z-20">
          {searchState === 'idle' && (
            <form onSubmit={handleManualSearch} className="bg-white dark:bg-slate-950 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-2xl p-2.5 flex items-center focus-within:ring-4 ring-blue-500/20 transition-all animate-in fade-in slide-in-from-bottom-10 duration-700 delay-300">
              <Search className="w-6 h-6 text-slate-400 ml-4 mr-3 shrink-0"/>
              <input type="text" placeholder={`Try it live: ${placeholderText}`} required value={domain} onChange={e=>setDomain(e.target.value)} className="w-full bg-transparent border-none focus:ring-0 text-xl py-3 outline-none font-bold text-slate-900 dark:text-white placeholder:text-slate-400" />
              <button type="submit" className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-xl font-black text-lg transition-all shadow-lg shadow-blue-600/20 hidden sm:flex shrink-0 hover:scale-105">Verify</button>
            </form>
          )}

          {/* THE API WATERFALL VISUALIZER */}
          {searchState === 'scanning' && (
            <div className="bg-[#0A0A0A] rounded-2xl border border-slate-800 p-8 shadow-2xl w-full mx-auto relative overflow-hidden animate-in fade-in zoom-in-95">
              <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-600 via-indigo-500 to-emerald-400 animate-pulse"></div>
              <div className="flex items-center justify-between mb-8">
                <div className="flex items-center gap-3"><Activity className="w-5 h-5 text-blue-500 animate-spin-slow"/><span className="font-mono text-sm font-bold text-white uppercase tracking-widest">Live Engine Tracing</span></div>
                <div className="font-mono text-xs text-slate-500 bg-slate-900 px-3 py-1 rounded-full border border-slate-800">Latency: <span className="text-emerald-400">142ms</span></div>
              </div>
              <div className="relative flex justify-between items-center px-4 md:px-10 h-32">
                <div className="absolute top-1/2 left-10 right-10 h-0.5 bg-slate-800 -translate-y-1/2 z-0">
                  <div className="h-full bg-blue-500 shadow-[0_0_15px_#3b82f6] animate-progress z-10"></div>
                </div>
                {[
                  { name: 'Syntax', delay: 0 }, { name: 'DNS / MX', delay: 400 },
                  { name: 'Spamhaus', delay: 800 }, { name: 'SMTP Ping', delay: 1200 }, { name: 'Catch-All', delay: 1600 }
                ].map((node, i) => (
                  <div key={i} className="relative z-20 flex flex-col items-center gap-3">
                    <div className="w-6 h-6 md:w-8 md:h-8 rounded-full bg-slate-900 border-2 border-slate-700 flex items-center justify-center transition-all duration-300" style={{ animation: `nodeActivate 0.2s ease-out ${node.delay}ms forwards` }}>
                      <div className="w-2 h-2 md:w-3 md:h-3 rounded-full bg-slate-600" style={{ animation: `coreActivate 0.2s ease-out ${node.delay}ms forwards` }}></div>
                    </div>
                    <span className="font-mono text-[10px] md:text-xs text-slate-400 absolute -bottom-8 whitespace-nowrap">{node.name}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {searchState === 'invalid' && (
            <div className="bg-white dark:bg-slate-950 rounded-[2rem] border border-slate-200 dark:border-slate-800 shadow-2xl p-8 text-left w-full mx-auto animate-in zoom-in-95">
              <div className="flex justify-between items-start mb-6">
                <div className="flex items-center gap-4"><div className="w-14 h-14 bg-red-50 dark:bg-red-900/20 rounded-2xl flex items-center justify-center"><AlertTriangle className="w-8 h-8 text-red-500"/></div><div><h3 className="text-2xl font-black text-slate-900 dark:text-white">{cleanDomain}</h3><p className="text-sm font-bold text-red-600 flex items-center gap-1">Verification Failed</p></div></div>
                <button onClick={() => {setSearchState('idle'); setDomain('');}} className="p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors"><X className="w-5 h-5"/></button>
              </div>
              <div className="bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl p-5 mb-6 text-center"><p className="text-slate-700 dark:text-slate-300 font-medium">We could not establish a connection to this domain's mail servers.</p></div>
              <button onClick={() => {setSearchState('idle'); setDomain('');}} className="w-full bg-slate-900 dark:bg-white text-white dark:text-slate-900 py-4 rounded-xl font-black shadow-lg hover:scale-[1.02] transition-transform">Try Another Domain</button>
            </div>
          )}

          {searchState === 'result' && (
            <div className="bg-white dark:bg-slate-950 rounded-[2rem] border border-slate-200 dark:border-slate-800 shadow-2xl p-8 relative overflow-hidden text-left w-full mx-auto animate-in zoom-in-95">
              <div className="absolute top-0 right-0 w-40 h-40 bg-emerald-500/10 rounded-full blur-[40px]"></div>
              <div className="flex justify-between items-start mb-6 relative z-10">
                <div className="flex items-center gap-4"><div className="w-14 h-14 bg-slate-50 dark:bg-slate-900 rounded-2xl flex items-center justify-center shadow-sm"><Globe className="w-8 h-8 text-blue-500"/></div><div><h3 className="text-2xl font-black text-slate-900 dark:text-white">{cleanDomain}</h3><p className="text-sm font-bold text-emerald-600 flex items-center gap-1"><CheckCircle2 className="w-4 h-4"/> Engine Complete</p></div></div>
                <button onClick={() => {setSearchState('idle'); setDomain('');}} className="p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors"><X className="w-5 h-5"/></button>
              </div>
              <div className="relative z-10">
                <div className="space-y-3 locked-blur">
                   <div className="flex justify-between p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800"><div className="flex items-center gap-3"><div className="w-8 h-8 bg-blue-100 dark:bg-blue-900/50 rounded-full"></div><span className="font-bold text-slate-700 dark:text-slate-300">John Doe • CEO</span></div><span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-1 rounded font-bold">100% Verified</span></div>
                   <div className="flex justify-between p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800"><div className="flex items-center gap-3"><div className="w-8 h-8 bg-purple-100 dark:bg-purple-900/50 rounded-full"></div><span className="font-bold text-slate-700 dark:text-slate-300">Sarah J. • VP Sales</span></div><span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-1 rounded font-bold">100% Verified</span></div>
                </div>
                <div className="absolute inset-0 flex flex-col items-center justify-center bg-gradient-to-t from-white via-white/90 to-transparent dark:from-slate-950 dark:via-slate-950/90 pt-12">
                   <div className="bg-slate-900 dark:bg-white p-6 rounded-2xl text-center w-[90%] max-w-sm mx-auto shadow-2xl border border-slate-800 dark:border-slate-200">
                     <Lock className="w-8 h-8 text-blue-500 mx-auto mb-3" />
                     <h4 className="font-black text-white dark:text-slate-900 text-xl mb-2">Results Locked</h4>
                     <button onClick={() => onOpenAuth('signup')} className="w-full bg-blue-600 hover:bg-blue-500 text-white py-3.5 rounded-xl font-bold transition-colors shadow-lg shadow-blue-600/20 flex items-center justify-center gap-2 mt-4 hover:scale-[1.02]">Unlock Free 150 Credits <ArrowRight className="w-4 h-4"/></button>
                   </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Buttons if idle */}
        {searchState === 'idle' && (
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 relative z-20 mb-12 animate-in fade-in slide-in-from-bottom-12 duration-700 delay-500">
            <button onClick={() => onOpenAuth('signup')} className="w-full sm:w-auto bg-blue-600 text-white px-10 py-5 rounded-2xl text-lg font-black transition-all shadow-xl shadow-blue-600/30 hover:scale-105 hover:bg-blue-500 flex items-center justify-center gap-2 group">
              Start verifying for free <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform"/>
            </button>
            <button onClick={() => onNavigateToPricing()} className="w-full sm:w-auto bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white px-10 py-5 rounded-2xl text-lg font-bold hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors flex items-center justify-center gap-2">
              <PlayCircle className="w-5 h-5 text-slate-400"/> View Pricing
            </button>
          </div>
        )}

        <div className="flex flex-col items-center gap-6 animate-in fade-in duration-700 delay-500 relative z-20">
          <div className="flex flex-wrap justify-center items-center gap-4 sm:gap-8 text-sm font-bold text-slate-500">
            <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500"/> No credit card required</div>
            <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500"/> 150 free credits</div>
            <div className="flex items-center gap-2 hidden md:flex"><CheckCircle2 className="w-4 h-4 text-emerald-500"/> 99.9% Accuracy</div>
          </div>
          <Badge color="gold">
            <Shield className="w-3 h-3 text-amber-600" /> 30-Day Money-Back Guarantee
          </Badge>
        </div>

        {/* THE DEV / SALES TOGGLE ILLUSION (ANIMATED) */}
        {searchState === 'idle' && (
          <div className="w-full max-w-5xl mx-auto mt-24 relative animate-in fade-in slide-in-from-bottom-24 duration-1000 delay-[600ms] z-30">
            <div className="flex justify-center mb-8 relative z-40">
              <div className="bg-slate-100 dark:bg-slate-900 p-1.5 rounded-full flex items-center border border-slate-200 dark:border-slate-800 shadow-sm">
                <button onClick={() => setViewMode('sales')} className={`px-6 py-2.5 rounded-full text-sm font-bold transition-all flex items-center gap-2 ${viewMode === 'sales' ? 'bg-white dark:bg-slate-800 text-blue-600 dark:text-blue-400 shadow-md' : 'text-slate-500 hover:text-slate-900 dark:hover:text-slate-300'}`}>
                  <Layers className="w-4 h-4"/> Dashboard UI
                </button>
                <button onClick={() => setViewMode('dev')} className={`px-6 py-2.5 rounded-full text-sm font-bold transition-all flex items-center gap-2 ${viewMode === 'dev' ? 'bg-slate-900 text-emerald-400 shadow-md' : 'text-slate-500 hover:text-slate-900 dark:hover:text-slate-300'}`}>
                  <Terminal className="w-4 h-4"/> Raw API
                </button>
              </div>
            </div>

            <div className="bg-[#0B0F19] rounded-2xl border border-slate-800 shadow-2xl relative overflow-hidden transition-all duration-500 transform hover:scale-[1.01] text-left">
              <div className="flex items-center gap-2 px-4 py-3 border-b border-slate-800 bg-[#050810]">
                <div className="w-3 h-3 rounded-full bg-[#ff5f56]"></div><div className="w-3 h-3 rounded-full bg-[#ffbd2e]"></div><div className="w-3 h-3 rounded-full bg-[#27c93f]"></div>
                <div className="mx-auto text-xs font-mono text-slate-500">{viewMode === 'sales' ? 'app.mailvah.com' : 'api.mailvah.com/v1/verify'}</div>
              </div>

              <div className="h-[450px] w-full bg-[#0B0F19] relative overflow-hidden">
                {/* STATE 1: LIVE SALES UI SIMULATION */}
                <div className={`absolute inset-0 transition-opacity duration-500 p-6 ${viewMode === 'sales' ? 'opacity-100 z-10' : 'opacity-0 pointer-events-none z-0'}`}>
                  <div className="flex items-center justify-between mb-8 relative z-20">
                    <div className="flex gap-4"><div className="w-32 h-8 bg-slate-800 rounded-lg"></div><div className="w-24 h-8 bg-slate-800/50 rounded-lg"></div></div>
                    <div className="w-40 h-10 bg-blue-600 rounded-xl flex items-center justify-center text-white text-xs font-bold gap-2 shadow-lg"><UploadCloud className="w-4 h-4"/> Bulk Upload</div>
                  </div>
                  
                  {/* Fake Cursor */}
                  <div className="absolute anim-cursor hidden md:block">
                    <MousePointer2 className="w-6 h-6 text-white fill-slate-900 drop-shadow-md"/>
                  </div>

                  {/* Simulated Upload Modal */}
                  <div className="absolute inset-0 bg-[#0B0F19]/80 backdrop-blur-sm flex items-center justify-center anim-modal">
                    <div className="bg-slate-900 border border-slate-800 p-8 rounded-2xl w-96 text-center shadow-2xl">
                      <Activity className="w-8 h-8 text-blue-500 animate-spin mx-auto mb-4"/>
                      <h3 className="text-white font-bold mb-4">Verifying leads.csv</h3>
                      <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden"><div className="bg-blue-500 h-full anim-bar"></div></div>
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-6 mb-8 relative z-10">
                    <div className="h-24 bg-slate-800/40 border border-slate-800 rounded-2xl p-4"><div className="w-1/2 h-4 bg-slate-700 rounded mb-4"></div><div className="w-3/4 h-8 bg-emerald-500/20 rounded"></div></div>
                    <div className="h-24 bg-slate-800/40 border border-slate-800 rounded-2xl p-4"><div className="w-1/2 h-4 bg-slate-700 rounded mb-4"></div><div className="w-1/2 h-8 bg-red-500/20 rounded"></div></div>
                    <div className="h-24 bg-slate-800/40 border border-slate-800 rounded-2xl p-4"><div className="w-1/2 h-4 bg-slate-700 rounded mb-4"></div><div className="w-2/3 h-8 bg-amber-500/20 rounded"></div></div>
                  </div>
                  <div className="space-y-3 relative z-10 anim-rows">
                     {[1,2,3].map(i => <div key={i} className="h-12 bg-slate-800/30 rounded-xl w-full flex items-center px-4 border border-slate-800/50"><div className="w-4 h-4 rounded-full bg-emerald-500/50 mr-4"></div><div className="h-3 bg-slate-700/50 w-1/3 rounded"></div></div>)}
                  </div>
                </div>

                {/* STATE 2: DEV RAW API SIMULATION */}
                <div className={`absolute inset-0 transition-opacity duration-500 p-8 font-mono text-sm leading-relaxed flex flex-col ${viewMode === 'dev' ? 'opacity-100 z-10' : 'opacity-0 pointer-events-none z-0'}`}>
                   {viewMode === 'dev' && <LiveDevLogs />}
                </div>
              </div>
            </div>
          </div>
        )}
      </section>

      {/* MARQUEE */}
      <section className="py-12 bg-white dark:bg-[#0B0F19] overflow-hidden relative border-b border-slate-100 dark:border-slate-800/50">
        <div className="absolute left-0 top-0 bottom-0 w-32 bg-gradient-to-r from-white dark:from-[#0B0F19] to-transparent z-10 pointer-events-none"></div>
        <div className="absolute right-0 top-0 bottom-0 w-32 bg-gradient-to-l from-white dark:from-[#0B0F19] to-transparent z-10 pointer-events-none"></div>
        <div className="flex whitespace-nowrap opacity-50 dark:opacity-30 hover:opacity-100 dark:hover:opacity-60 transition-all duration-500 grayscale hover:grayscale-0">
          <div className="animate-marquee flex items-center justify-around w-full">
            {["Acme Corp", "TechFlow", "Growthly", "Scaleup", "Velocity", "Donmican Tech"].map((name, i) => (
               <span key={i} className="text-2xl font-black tracking-tight text-slate-800 dark:text-slate-200 mx-12">{name}</span>
            ))}
          </div>
          <div className="animate-marquee flex items-center justify-around w-full" aria-hidden="true">
            {["Acme Corp", "TechFlow", "Growthly", "Scaleup", "Velocity", "Donmican Tech"].map((name, i) => (
               <span key={i} className="text-2xl font-black tracking-tight text-slate-800 dark:text-slate-200 mx-12">{name}</span>
            ))}
          </div>
        </div>
      </section>

      {/* INTERACTIVE ROI CALCULATOR */}
      <section className="py-24 bg-slate-50 dark:bg-slate-900/30 border-y border-slate-200 dark:border-slate-800/50 relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <Badge color="emerald">The ROI of Accuracy</Badge>
              <h2 className="text-4xl md:text-5xl font-black text-slate-900 dark:text-white mb-6 leading-tight">Stop burning your pipeline.</h2>
              <p className="text-xl text-slate-500 dark:text-slate-400 mb-8 font-medium leading-relaxed">
                Every bounced email doesn't just waste a lead—it damages your domain reputation. If your bounce rate creeps over 3%, Google and Microsoft start sending your emails directly to spam. 
              </p>
              <ul className="space-y-5 mb-10">
                <li className="flex items-center gap-4 text-lg font-bold text-slate-700 dark:text-slate-300"><div className="w-8 h-8 rounded-full bg-red-100 text-red-600 flex items-center justify-center shrink-0"><TrendingDown className="w-4 h-4"/></div> Average B2B list decay is 3% per month.</li>
                <li className="flex items-center gap-4 text-lg font-bold text-slate-700 dark:text-slate-300"><div className="w-8 h-8 rounded-full bg-amber-100 text-amber-600 flex items-center justify-center shrink-0"><AlertTriangle className="w-4 h-4"/></div> A 5% bounce rate triggers Google Spam filters.</li>
                <li className="flex items-center gap-4 text-lg font-bold text-slate-700 dark:text-slate-300"><div className="w-8 h-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center shrink-0"><CheckCircle2 className="w-4 h-4"/></div> Mailvah guarantees a bounce rate under 1%.</li>
              </ul>
            </div>

            <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-10 border border-slate-200 dark:border-slate-800 shadow-2xl relative bento-card">
              <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-[60px] pointer-events-none"></div>
              <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-8">Calculate your savings</h3>
              
              <div className="space-y-8">
                <div>
                  <div className="flex justify-between text-sm font-bold text-slate-500 dark:text-slate-400 mb-4"><span>Monthly Emails Sent</span><span className="text-slate-900 dark:text-white">{volume.toLocaleString()}</span></div>
                  <input type="range" min="0" max={pricingTiers.length - 1} step="1" value={sliderIndex} onChange={(e) => setSliderIndex(parseInt(e.target.value))} className="w-full relative z-20" />
                </div>
                <div>
                  <div className="flex justify-between text-sm font-bold text-slate-500 dark:text-slate-400 mb-4"><span>Current Bounce Rate</span><span className="text-red-500 dark:text-red-400">8%</span></div>
                  <input type="range" min="1" max="15" value="8" readOnly className="w-full pointer-events-none opacity-80" />
                </div>
              </div>

              <div className="mt-10 pt-8 border-t border-slate-100 dark:border-slate-800 grid grid-cols-2 gap-6">
                 <div>
                   <div className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-2">Leads Wasted</div>
                   <div className="text-3xl font-black text-red-500">{wastedLeads.toLocaleString()}<span className="text-lg">/mo</span></div>
                 </div>
                 <div>
                   <div className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-2">Mailvah ROI</div>
                   <div className="text-3xl font-black text-emerald-500 dark:text-emerald-400">+${savings.toLocaleString()}<span className="text-lg">/mo</span></div>
                 </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* LIVE PLATFORM TOUR (THE 4 TAB DEMO) */}
      <LivePlatformTour />

      {/* EXPANDED BENTO BOX FEATURES */}
      <section id="features" className="py-32 px-6 max-w-7xl mx-auto">
        <div className="text-center mb-20">
          <Badge color="blue">The Engine</Badge>
          <h2 className="text-4xl md:text-6xl font-black text-slate-900 dark:text-white mt-4 mb-6 tracking-tight leading-[1.1]">Everything you need to scale.</h2>
          <p className="text-xl text-slate-500 dark:text-slate-400 max-w-2xl mx-auto font-medium leading-relaxed">We stripped away the bloat and focused entirely on data accuracy, speed, and seamless integration.</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-[minmax(280px,auto)]">
          <div className="md:col-span-2 bg-slate-900 rounded-[2.5rem] p-10 relative overflow-hidden bento-card group border border-slate-800">
            <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-blue-600/20 rounded-full blur-[100px] group-hover:bg-blue-500/30 transition-colors"></div>
            <div className="relative z-10 flex flex-col h-full justify-between">
              <div>
                <Badge color="blue">Core Tech</Badge>
                <h3 className="text-3xl font-black text-white mt-4 mb-4 leading-tight">Live SMTP Verification <br/>Engine.</h3>
                <p className="text-slate-400 text-lg font-medium max-w-md">Databases decay at 3% a month. We don't rely on cached data. We ping the mail server in real-time before you pay a credit.</p>
              </div>
              <div className="mt-10 bg-slate-950 rounded-2xl border border-slate-800 p-4 flex items-center gap-4 w-max">
                <div className="w-3 h-3 rounded-full bg-emerald-500 animate-pulse"></div>
                <code className="text-sm font-mono text-emerald-400">250 2.1.5 Recipient &lt;ceo@acme.com&gt; OK</code>
              </div>
            </div>
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-10 border border-slate-200 dark:border-slate-800 shadow-sm bento-card flex flex-col justify-between group">
            <div>
              <div className="w-12 h-12 bg-blue-50 dark:bg-blue-900/30 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform"><Chrome className="w-6 h-6 text-blue-600 dark:text-blue-400"/></div>
              <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-3">LinkedIn Extractor</h3>
              <p className="text-slate-500 dark:text-slate-400 font-medium">Extract verified emails directly over LinkedIn profiles and Sales Navigator searches.</p>
            </div>
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-10 border border-slate-200 dark:border-slate-800 shadow-sm bento-card flex flex-col justify-between group">
            <div>
              <div className="w-12 h-12 bg-emerald-50 dark:bg-emerald-900/30 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform"><Database className="w-6 h-6 text-emerald-600 dark:text-emerald-400"/></div>
              <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-3">Bulk Enrichment</h3>
              <p className="text-slate-500 dark:text-slate-400 font-medium">Upload messy CSV lists of names and domains. Our Redis workers enrich thousands of rows in minutes.</p>
            </div>
          </div>

          <div className="bg-gradient-to-br from-slate-50 to-blue-50/50 dark:from-slate-900 dark:to-slate-800/50 rounded-[2.5rem] p-10 border border-slate-200 dark:border-slate-800 shadow-sm bento-card flex flex-col justify-center text-left">
             <Workflow className="w-12 h-12 text-blue-500 mb-6"/>
             <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-4">1-Click CRM Purge</h3>
             <p className="text-slate-500 dark:text-slate-400 font-medium">Push verified leads straight to HubSpot/Salesforce. We detect existing contacts to prevent duplicates.</p>
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-10 border border-slate-200 dark:border-slate-800 shadow-sm bento-card flex flex-col justify-center text-left">
             <Shield className="w-12 h-12 text-amber-500 mb-6"/>
             <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-4">Blacklist Monitor</h3>
             <p className="text-slate-500 dark:text-slate-400 font-medium">Constant, automated domain monitoring against global Spamhaus and Barracuda blacklists.</p>
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-10 border border-slate-200 dark:border-slate-800 shadow-sm bento-card flex flex-col justify-center text-left">
             <Search className="w-12 h-12 text-purple-500 mb-6"/>
             <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-4">Permutation Finder</h3>
             <p className="text-slate-500 dark:text-slate-400 font-medium">Only have a name and company? We test every combination. (Sandbox plan: Guess 5/day free).</p>
          </div>
        </div>
      </section>

      {/* WALL OF LOVE (TESTIMONIALS) */}
      <section className="py-24 bg-slate-50 dark:bg-slate-900/50 border-y border-slate-200 dark:border-slate-800/50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black text-slate-900 dark:text-white mb-6">Trusted by modern revenue teams.</h2>
            <div className="flex justify-center items-center gap-1">
              {[1,2,3,4,5].map(i => <Star key={i} className="w-6 h-6 text-amber-400 fill-amber-400" />)}
            </div>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { quote: "We switched from our old provider and our bounce rate dropped from 8% to 0.4%. The ROI was immediate.", name: "Sarah Jenkins", role: "VP Sales, TechFlow", metric: "Saved $12k/yr" },
              { quote: "The API is blazing fast. We integrated Mailvah into our automated lead scoring in under an hour.", name: "David Chen", role: "Growth Eng, Growthly", metric: "<200ms API" },
              { quote: "I love that unused credits roll over. It makes budgeting for our agency so much more predictable.", name: "Elena Rodriguez", role: "Founder, Scaleup Agency", metric: "0 wasted credits" }
            ].map((t, i) => (
              <div key={i} className="bg-white dark:bg-slate-800 p-8 rounded-3xl border border-slate-200 dark:border-slate-700 shadow-sm relative bento-card">
                <Quote className="w-10 h-10 text-blue-100 dark:text-blue-900/50 absolute top-6 right-6" />
                <p className="text-slate-700 dark:text-slate-300 font-medium leading-relaxed mb-6 relative z-10">"{t.quote}"</p>
                <div className="flex items-center justify-between border-t border-slate-100 dark:border-slate-700 pt-6">
                  <div>
                    <div className="font-bold text-slate-900 dark:text-white">{t.name}</div>
                    <div className="text-sm text-slate-500 dark:text-slate-400">{t.role}</div>
                  </div>
                  <div className="bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-xs font-bold px-3 py-1.5 rounded-lg border border-emerald-100 dark:border-emerald-500/20">
                    {t.metric}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 3-TIER ENTERPRISE PRICING OVERHAUL */}
      <section id="pricing" className="py-32 relative text-center px-4 overflow-hidden">
         <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-blue-600/5 rounded-full blur-[100px] pointer-events-none"></div>
         <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-indigo-600/5 rounded-full blur-[100px] pointer-events-none"></div>
         
         <div className="relative z-10 max-w-7xl mx-auto">
           <div className="inline-block bg-gradient-to-r from-blue-600 to-indigo-600 text-white px-6 py-2 rounded-full font-black text-sm uppercase tracking-widest shadow-lg shadow-blue-500/20 mb-6">
             10x the value. 60% the cost.
           </div>
           <h2 className="text-4xl md:text-6xl font-black text-slate-900 dark:text-white mb-6 tracking-tight">Fair pricing. Zero waste.</h2>
           <p className="text-xl text-slate-500 mb-10 max-w-2xl mx-auto">Start free, upgrade when you need to. Unused credits roll over forever.</p>
           
           <div className="inline-flex items-center p-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl shadow-sm mb-16">
              <button onClick={() => setAnnualBilling(false)} className={`px-8 py-3 rounded-lg text-sm font-bold transition-all ${!annualBilling ? 'bg-slate-900 dark:bg-blue-600 shadow-md text-white' : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'}`}>Monthly</button>
              <button onClick={() => setAnnualBilling(true)} className={`px-8 py-3 rounded-lg text-sm font-bold transition-all flex items-center gap-2 ${annualBilling ? 'bg-slate-900 dark:bg-blue-600 shadow-md text-white' : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'}`}>Annual <span className="px-2 py-0.5 rounded text-[10px] font-black uppercase bg-emerald-500/20 text-emerald-500">2 months free</span></button>
           </div>

           <div className="grid lg:grid-cols-3 md:grid-cols-2 gap-8 text-left items-stretch">
             {/* Sandbox Tier */}
             <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-10 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col hover:border-blue-300 transition-colors">
               <div className="mb-6"><Badge color="emerald">Forever Free</Badge><h3 className="text-3xl font-black text-slate-900 dark:text-white">Sandbox</h3></div>
               <div className="text-5xl font-black mb-8 text-slate-900 dark:text-white">$0<span className="text-lg text-slate-500">/mo</span></div>
               <ul className="space-y-4 mb-10 flex-grow">
                 <li className="flex items-center gap-3 text-sm text-slate-600 dark:text-slate-300 font-bold"><CheckCircle2 className="w-5 h-5 text-slate-300 dark:text-slate-600 shrink-0" /> 150 verification credits</li>
                 <li className="flex items-center gap-3 text-sm text-slate-600 dark:text-slate-300 font-bold"><CheckCircle2 className="w-5 h-5 text-slate-300 dark:text-slate-600 shrink-0" /> Spam-proof Composer</li>
                 <li className="flex items-center gap-3 text-sm text-slate-600 dark:text-slate-300 font-bold"><CheckCircle2 className="w-5 h-5 text-slate-300 dark:text-slate-600 shrink-0" /> Permutation Finder (5/day)</li>
               </ul>
               <button onClick={() => onOpenAuth('signup')} className="w-full py-4 rounded-xl font-bold bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-white hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors">Start Free</button>
             </div>
             
             {/* Pro Network Tier */}
             <div className="bg-slate-900 rounded-[2.5rem] p-10 shadow-2xl relative overflow-hidden transform lg:scale-[1.05] z-10 flex flex-col border border-slate-800">
               <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-blue-600/20 rounded-full blur-[80px]"></div>
               <div className="relative z-10 flex flex-col h-full">
                 <div className="mb-6"><Badge color="blue">Pro Network</Badge><h3 className="text-3xl font-black text-white">Scale outreach</h3></div>
                 <div className="text-5xl font-black mb-8 text-white">${displayPrice}<span className="text-lg text-blue-200">/mo</span></div>
                 <input type="range" min="0" max={pricingTiers.length - 1} step="1" value={sliderIndex} onChange={(e) => setSliderIndex(parseInt(e.target.value))} className="w-full mb-8 relative z-20"/>
                 <div className="text-center mb-8 font-bold text-xl text-white">{currentTier.credits.toLocaleString()} Verification Credits</div>
                 <ul className="space-y-4 mb-10 flex-grow text-slate-300">
                   <li className="flex items-center gap-3 text-sm font-bold"><CheckCircle2 className="w-5 h-5 text-blue-500 shrink-0" /> Infinite Rollover Credits</li>
                   <li className="flex items-center gap-3 text-sm font-bold"><CheckCircle2 className="w-5 h-5 text-blue-500 shrink-0" /> Bulk CSV Verifier</li>
                   <li className="flex items-center gap-3 text-sm font-bold"><CheckCircle2 className="w-5 h-5 text-blue-500 shrink-0" /> 1-Click CRM Purge (HubSpot)</li>
                 </ul>
                 <button onClick={() => onOpenAuth('signup')} className="w-full py-4 rounded-xl font-bold bg-blue-600 text-white hover:bg-blue-500 transition-colors shadow-lg shadow-blue-900/50 hover:scale-[1.02]">Upgrade to Pro</button>
               </div>
             </div>

             {/* Enterprise Custom Tier */}
             <div className="bg-[#050810] rounded-[2.5rem] p-10 border border-slate-800 shadow-xl flex flex-col hover:border-slate-600 transition-colors relative overflow-hidden group">
               <div className="absolute inset-0 bg-gradient-to-b from-slate-800/20 to-transparent pointer-events-none"></div>
               <div className="relative z-10 flex flex-col h-full">
                 <div className="mb-6"><Badge color="purple">100k+ Volume</Badge><h3 className="text-3xl font-black text-white">Enterprise</h3></div>
                 <div className="text-5xl font-black mb-8 text-white">Custom</div>
                 <p className="text-slate-400 font-medium mb-8">For high-volume senders, lead gen agencies, and complex setups.</p>
                 <ul className="space-y-4 mb-10 flex-grow">
                   <li className="flex items-center gap-3 text-sm text-slate-300 font-bold"><CheckCircle2 className="w-5 h-5 text-purple-500 shrink-0" /> Dedicated IP Infrastructure</li>
                   <li className="flex items-center gap-3 text-sm text-slate-300 font-bold"><CheckCircle2 className="w-5 h-5 text-purple-500 shrink-0" /> Sub-200ms API Access</li>
                   <li className="flex items-center gap-3 text-sm text-slate-300 font-bold"><CheckCircle2 className="w-5 h-5 text-purple-500 shrink-0" /> Deep Catch-All Resolution</li>
                 </ul>
                 <button className="w-full py-4 rounded-xl font-bold bg-white text-slate-900 hover:bg-slate-200 transition-colors">Talk to Founders</button>
               </div>
             </div>

           </div>
           
           <div className="mt-12 flex justify-center">
             <Badge color="gold">
               <Shield className="w-4 h-4 text-amber-600" /> 30-Day Money-Back Guarantee
             </Badge>
           </div>
         </div>
      </section>

      {/* FINAL CTA */}
      <section className="py-32 bg-slate-900 dark:bg-[#050810] text-center px-6 relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-blue-600/10 rounded-full blur-[100px] pointer-events-none"></div>
        <div className="relative z-10 max-w-4xl mx-auto">
          <h2 className="text-5xl md:text-7xl font-black text-white mb-8 leading-tight tracking-tight">Ready to build your<br/>pipeline?</h2>
          <p className="text-xl text-slate-400 mb-12 font-medium max-w-2xl mx-auto">Join thousands of founders and sales teams who have switched to Mailvah for better data and transparent pricing.</p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <button onClick={() => onOpenAuth('signup')} className="px-10 py-5 bg-blue-600 text-white rounded-2xl font-black text-lg hover:bg-blue-500 transition-all shadow-xl shadow-blue-600/30 hover:scale-105">Get started for free</button>
            <button className="px-10 py-5 bg-[#1e293b] text-white rounded-2xl font-black text-lg hover:bg-slate-800 border border-slate-700 flex items-center justify-center gap-2"><PlayCircle className="w-5 h-5"/> Watch demo</button>
          </div>
          <div className="mt-8 flex justify-center">
            <Badge color="gold"><Shield className="w-4 h-4 text-amber-600" /> 30-Day Money-Back Guarantee</Badge>
          </div>
        </div>
      </section>
    </div>
  );
};

// --- COMPARE PAGE COMPONENT ---
const ComparePage = ({ params, navigate }) => {
  useEffect(() => window.scrollTo(0, 0), [params]);
  const data = COMPETITORS[params] || COMPETITORS['apollo'];

  return (
    <main className="max-w-6xl mx-auto px-6 py-32 page-transition flex-1">
      <div className="text-center mb-20">
        <Badge color="blue">Mailvah vs The Market</Badge>
        <h1 className="text-5xl md:text-6xl font-black text-slate-900 dark:text-white mt-4 mb-6">Mailvah vs {data.name}</h1>
        <p className="text-2xl text-slate-600 dark:text-slate-400 font-medium">{data.tagline}</p>
      </div>

      <div className="grid lg:grid-cols-3 gap-10 mb-16">
        <div className="lg:col-span-2 space-y-8">
           <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-200 dark:border-slate-800 p-10 shadow-xl">
             <h2 className="text-2xl font-black mb-8 flex items-center gap-2 text-slate-900 dark:text-white"><Zap className="text-blue-500"/> Feature Showdown</h2>
             <div className="divide-y divide-slate-100 dark:divide-slate-800">
               <div className="grid grid-cols-3 py-4 font-bold text-slate-500 uppercase tracking-wider text-xs"><div>Feature</div><div className="text-center text-blue-600">Mailvah</div><div className="text-center">{data.name}</div></div>
               {data.features.map((f, i) => (
                  <div key={i} className="grid grid-cols-3 py-6 items-center"><div className="font-medium text-slate-900 dark:text-white pr-4">{f.name}</div><div className="flex justify-center">{f.us ? <CheckCircle2 className="text-emerald-500 w-6 h-6"/> : <X className="text-slate-300 w-6 h-6"/>}</div><div className="flex justify-center">{f.them ? <CheckCircle2 className="text-slate-400 w-6 h-6"/> : <X className="text-red-400 w-6 h-6"/>}</div></div>
               ))}
             </div>
           </div>
           
           <div className="bg-gradient-to-br from-blue-600 to-indigo-700 text-white rounded-[2.5rem] p-10 shadow-xl relative overflow-hidden">
             <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-[60px]"></div>
             <div className="relative z-10">
               <h3 className="text-2xl font-black mb-4 flex items-center gap-3"><Zap className="w-6 h-6 text-amber-400" /> Why Mailvah is the Top Pick</h3>
               <p className="text-lg text-blue-50 font-medium leading-relaxed mb-8">{data.overview}</p>
               <button onClick={() => navigate('home')} className="bg-white text-blue-700 hover:bg-blue-50 px-8 py-4 rounded-xl font-bold hover:scale-[1.02] transition-transform shadow-lg flex items-center gap-2 group">Switch today <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform"/></button>
             </div>
           </div>
        </div>

        <div className="space-y-8">
           <div className="bg-white dark:bg-slate-900 rounded-[2rem] border border-slate-200 dark:border-slate-800 p-8 shadow-sm">
             <h3 className="text-xl font-black mb-6 text-slate-900 dark:text-white">Pricing Comparison</h3>
             <div className="space-y-6">
                <div><p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Mailvah</p><p className="text-2xl font-black text-blue-600">{data.pricing.mailvah}</p></div>
                <div className="pt-4 border-t border-slate-100 dark:border-slate-800"><p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">{data.name}</p><p className="text-xl font-bold text-slate-700 dark:text-slate-300">{data.pricing.competitor}</p></div>
             </div>
           </div>
           <div className="bg-slate-900 text-white rounded-[2rem] p-8 relative overflow-hidden">
             <Quote className="w-16 h-16 text-slate-800 absolute top-4 right-4" />
             <p className="text-lg font-medium leading-relaxed mb-6 relative z-10">"{data.testimonial.quote}"</p>
             <p className="font-bold text-blue-400 relative z-10 text-sm">— {data.testimonial.author}</p>
           </div>
        </div>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-200 dark:border-slate-800 p-10 shadow-sm max-w-3xl mx-auto">
        <h3 className="text-2xl font-black mb-8 text-slate-900 dark:text-white">How to switch from {data.name}</h3>
        <div className="space-y-6">
          {data.guide.map((step, i) => (
            <div key={i} className="flex items-start gap-4"><div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-black shrink-0 mt-1">{i + 1}</div><p className="text-lg text-slate-700 dark:text-slate-300 pt-1 font-medium">{step.replace(/^\d+\.\s/, '')}</p></div>
          ))}
        </div>
      </div>
    </main>
  );
};

// --- LEGAL PAGE COMPONENT ---
const LegalPage = ({ params }) => {
  useEffect(() => window.scrollTo(0, 0), [params]);
  const data = LEGAL_DATA[params] || LEGAL_DATA['privacy'];

  return (
    <main className="pt-32 pb-24 max-w-4xl mx-auto px-6 page-transition flex-1">
      <div className="mb-12">
        <Badge color="purple">Legal & Trust</Badge>
        <h1 className="text-4xl md:text-6xl font-black text-slate-900 dark:text-white mt-6 mb-6 tracking-tight">{data.title}</h1>
        <p className="text-sm font-bold text-slate-400 uppercase tracking-wider">Effective Date: {data.date}</p>
      </div>
      <div className="max-w-none">
        <p className="text-xl text-slate-600 dark:text-slate-300 leading-relaxed mb-12 font-medium">{data.intro}</p>
        <div className="space-y-12">
          {data.sections.map((section, idx) => (
            <div key={idx} className="bg-slate-50 dark:bg-slate-800/50 p-8 rounded-3xl border border-slate-100 dark:border-slate-800">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">{section.heading}</h2>
              <div className="text-slate-600 dark:text-slate-400 leading-relaxed space-y-4 font-medium text-[17px]">
                {section.body.map((p, i) => <p key={i}>{p}</p>)}
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
};

// --- DASHBOARD COMPONENT ---
const Dashboard = ({ navigate }) => {
  useEffect(() => window.scrollTo(0, 0), []);
  const [activeTab, setActiveTab] = useState('composer');
  
  const [composerInput, setComposerInput] = useState('');
  const [composerSpamCount, setComposerSpamCount] = useState(0);
  const [bulkProcessing, setBulkProcessing] = useState(false);
  const [bulkProgress, setBulkProgress] = useState(0);
  const [bulkResult, setBulkResult] = useState(null);

  const NavBtn = ({ id, icon: Icon, label, tier }) => (
    <button onClick={() => setActiveTab(id)} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl font-bold text-sm transition-colors ${activeTab === id ? 'bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-800'}`}><Icon className="w-4 h-4" /> {label} {tier === 'pro' && activeTab !== id && <Lock className="w-3 h-3 ml-auto opacity-50" />}</button>
  );

  const handleBulkUpload = () => {
    setBulkProcessing(true); setBulkProgress(0); setBulkResult(null);
    let p = 0;
    const interval = setInterval(() => {
      p += 8; setBulkProgress(Math.min(p, 100));
      if (p >= 100) { clearInterval(interval); setBulkProcessing(false); setBulkResult({ valid: 8420, invalid: 1200, catchAll: 380 }); }
    }, 400);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#0B0F19] flex pt-20 lg:pt-0">
      <div className="w-72 fixed h-full border-r border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hidden lg:flex flex-col z-10 px-4 py-6">
        <div className="flex items-center gap-2.5 mb-8 px-2 cursor-pointer" onClick={() => navigate('home')}><div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center"><Mail className="w-4 h-4 text-white" /></div><span className="font-black text-xl text-slate-900 dark:text-white">Mailvah.</span></div>
        <div className="space-y-1 flex-1 overflow-y-auto scrollbar-hide">
          <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest px-3 mb-2 mt-4">Sandbox Tools</div>
          <NavBtn id="composer" icon={PenTool} label="Spam-Proof Composer" />
          <NavBtn id="finder" icon={Search} label="Permutation Finder" />
          <div className="text-[10px] font-black text-blue-500 uppercase tracking-widest px-3 mb-2 mt-8">Pro Network</div>
          <NavBtn id="bulk" icon={UploadCloud} label="Bulk CSV Verifier" tier="pro" />
          <NavBtn id="domain" icon={ShieldCheck} label="Domain Monitor" tier="pro" />
        </div>
        <div className="pt-4 border-t border-slate-200 dark:border-slate-800"><button onClick={() => navigate('home')} className="w-full flex items-center gap-3 px-4 py-3 rounded-xl font-bold text-sm text-slate-500 hover:text-red-500 transition-colors"><LogOut className="w-4 h-4" /> Sign Out</button></div>
      </div>

      <div className="flex-1 lg:ml-72 px-6 md:px-12 py-10 overflow-y-auto min-h-screen">
        {activeTab === 'composer' && (
          <div className="max-w-4xl mx-auto page-transition">
             <div className="mb-8"><Badge color="emerald">Free Sandbox Tool</Badge><h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight mb-2">Spam-Proof Composer</h2><p className="text-slate-500 font-medium">Type a spam word like "100% free" to test the defense engine.</p></div>
             <div className="grid md:grid-cols-2 gap-8">
               <textarea value={composerInput} onChange={(e) => { setComposerInput(e.target.value); setComposerSpamCount((e.target.value.toLowerCase().match(new RegExp(spamWords.join('|'), 'g')) || []).length); }} placeholder="Draft your cold email here..." className="w-full h-96 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 outline-none focus:ring-2 focus:ring-blue-500 resize-none font-medium text-slate-900 dark:text-white shadow-sm"/>
               <div className="bg-slate-900 rounded-3xl p-8 border border-slate-800 flex flex-col relative overflow-hidden shadow-2xl">
                 <div className="flex items-center gap-2 mb-6 border-b border-slate-800 pb-4"><ShieldCheck className="w-5 h-5 text-emerald-500" /><span className="font-bold text-white">Spam Defense Console</span></div>
                 {composerSpamCount > 0 ? (
                   <div className="bg-red-500/20 border border-red-500/50 p-4 rounded-xl flex items-start gap-3 animate-in fade-in"><AlertTriangle className="w-5 h-5 text-red-400 shrink-0"/><div className="text-sm text-red-300 font-bold">Detected {composerSpamCount} dangerous trigger(s). Your email will likely bounce.</div></div>
                 ) : (
                   <div className="flex-1 flex flex-col items-center justify-center text-emerald-500/50"><CheckCircle className="w-16 h-16 mb-4 opacity-50"/><p className="font-bold text-center">Inbox Safe.<br/>No spam triggers detected.</p></div>
                 )}
               </div>
             </div>
          </div>
        )}
        
        {activeTab === 'bulk' && (
          <div className="max-w-4xl mx-auto page-transition">
             <div className="mb-8"><Badge color="blue">Pro Network Feature</Badge><h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight mb-2">Bulk CSV Verifier</h2><p className="text-slate-500 font-medium">Upload raw exports. We securely stream this to our Background Worker Node.</p></div>
             
             {!bulkProcessing && !bulkResult && (
               <div onClick={handleBulkUpload} className="bg-white dark:bg-slate-900 border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-3xl p-16 text-center cursor-pointer hover:border-blue-500 transition-colors group shadow-sm">
                 <div className="w-20 h-20 bg-blue-50 dark:bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-6 group-hover:scale-110 transition-transform"><FileUp className="w-10 h-10 text-blue-500" /></div>
                 <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-2">Click to Simulate Upload</h3><p className="text-slate-500 font-medium">Up to 100,000 rows per file.</p>
               </div>
             )}

             {bulkProcessing && (
               <div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 p-10 shadow-sm text-center">
                 <Activity className="w-12 h-12 text-blue-500 animate-spin mx-auto mb-6"/>
                 <h3 className="text-xl font-black text-slate-900 dark:text-white mb-2">Executing BullMQ Workers...</h3>
                 <div className="w-full bg-slate-100 dark:bg-slate-800 rounded-full h-3 mb-4 overflow-hidden"><div className="bg-blue-600 h-3 rounded-full transition-all duration-300" style={{width: `${bulkProgress}%`}}></div></div>
                 <p className="font-bold text-blue-600">{bulkProgress}% Complete</p>
               </div>
             )}

             {bulkResult && (
               <div className="animate-in fade-in">
                 <div className="bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800/50 rounded-3xl p-8 flex justify-between items-center mb-8">
                   <div className="flex items-center gap-4"><div className="w-14 h-14 bg-emerald-100 dark:bg-emerald-900/50 rounded-full flex items-center justify-center"><CheckCircle className="text-emerald-600 dark:text-emerald-400 w-8 h-8" /></div><div><h3 className="text-emerald-900 dark:text-emerald-400 font-black text-xl">Refinery Complete</h3><p className="text-emerald-700 dark:text-emerald-500 font-bold">10,000 rows processed.</p></div></div>
                   <button onClick={() => setBulkResult(null)} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 px-6 py-3 rounded-xl font-bold hover:bg-slate-50 transition-colors">Start New Job</button>
                 </div>
                 <div className="grid md:grid-cols-3 gap-6 mb-8">
                   <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 border-t-4 border-t-emerald-500 shadow-sm"><div className="text-sm font-bold text-slate-500 mb-2">Diamond Leads (Valid)</div><div className="text-4xl font-black text-slate-900 dark:text-white">{bulkResult.valid}</div></div>
                   <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 border-t-4 border-t-red-500 shadow-sm"><div className="text-sm font-bold text-slate-500 mb-2">Invalid (Bounces)</div><div className="text-4xl font-black text-slate-900 dark:text-white">{bulkResult.invalid}</div></div>
                   <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 border-t-4 border-t-amber-500 shadow-sm"><div className="text-sm font-bold text-slate-500 mb-2">Risky (Catch-Alls)</div><div className="text-4xl font-black text-slate-900 dark:text-white">{bulkResult.catchAll}</div></div>
                 </div>
                 <button className="w-full bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-black py-5 rounded-xl shadow-lg hover:scale-[1.02] transition-transform">Download Verified CSV</button>
               </div>
             )}
          </div>
        )}
      </div>
    </div>
  );
};

// --- MAIN APP COMPONENT ---
export default function Page() {
  const [route, setRoute] = useState({ path: 'home', param: null });
  const [isDark, setIsDark] = useState(false);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [authMode, setAuthMode] = useState('login');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setIsDark(document.documentElement.classList.contains('dark'));
    }
  }, []);

  const toggleTheme = () => {
    setIsDark(!isDark);
    if (!isDark) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  };

  const navigate = (path, param = null) => {
    setRoute({ path, param });
    window.scrollTo(0, 0);
  };

  const handleLoginSuccess = () => {
    setIsLoggedIn(true);
    navigate('dashboard');
  };

  const isDashboard = route.path === 'dashboard';

  return (
    <div className={`${isDark ? 'dark' : ''}`}>
      <div className="min-h-screen bg-white dark:bg-[#0B0F19] text-slate-900 dark:text-white font-sans selection:bg-blue-200 selection:text-blue-900 flex flex-col transition-colors duration-300">
        
        <Navbar 
          isDark={isDark} 
          toggleTheme={toggleTheme} 
          isLoggedIn={isLoggedIn} 
          onOpenAuth={(mode) => { setAuthMode(mode); setIsAuthModalOpen(true); }} 
          navigate={navigate} 
          currentRoute={route} 
        />
        
        {route.path === 'home' && (
          <LandingPage 
            onOpenAuth={(mode) => { setAuthMode(mode); setIsAuthModalOpen(true); }} 
            onNavigateToPricing={() => { document.getElementById('pricing')?.scrollIntoView({ behavior: 'smooth' }); }} 
          />
        )}
        
        {route.path === 'compare' && <ComparePage params={route.param} navigate={navigate} />}
        {route.path === 'legal' && <LegalPage params={route.param} />}
        {route.path === 'dashboard' && <Dashboard navigate={navigate} />}

        {!isDashboard && <Footer navigate={navigate} />}

        <AuthModal 
          isOpen={isAuthModalOpen} 
          onClose={() => setIsAuthModalOpen(false)} 
          initialMode={authMode} 
          onLoginSuccess={handleLoginSuccess} 
        />
      </div>
    </div>
  );
}
